# Generated by Django 3.2.16 on 2025-05-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250515_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='related_name',
        ),
    ]
